language: groovy
jdk: 
     - oraclejdk8

env:
     - GRAILS_VERSION=2.3.11

branches:
  only:
    - master

before_script:
     - chmod +x grailsw

script: ./grailsw refresh-dependencies
     && ./grailsw test-app -- stacktrace