language: groovy
jdk: 
     - oraclejdk8
     - oraclejdk7
     - openjdk7

env:
     - GRAILS_VERSION=2.3.11

branches:
  only:
    - master

before_script:
     - chmod +x grailsw

script: ./grailsw refresh-dependencies
     && ./grailsw test-app -- stacktrace

deploy:
  provider: heroku
  app: chessmind
  api_key: "705b95af-8660-4935-ad4e-acb9991943c5"
  strategy: git
  on:
    branch: master
